config/routes.rb
Rails.application.routes.draw do
  get "services/create"
  root 'static_pages#home'
  resources :users
  resources :sessions, only: [:new,:create,:destroy]
  resources :meeting_rooms, only: [:index,:new,:create,:show]
  resources :images, only: [:index,:create,:destroy]
  resource :settings, only: [:edit,:update]
  resources :suggestions, only: [:new,:create]
  resources :bookings, only: [:index,:new,:create]
  resources :services, only: [:index,:new,:edit,:create,:update,:show]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/service.rb
class Service < ActiveRecord::Base
  validates :name, presence: true
  has_many :features
  has_many :meeting_rooms, through: :features
  mount_uploader :photo_file, IconUploader
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :restrict_access, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :admin_user, only: :destroy
  
  def index
    @services = Service.all
  end
  
  def new
    @service = Service.new
  end
  
  def edit
    @service = Service.find(params[:id])
  end
  
  def show
    @service = Service.find(params[:id])
  end
  
  def create
    @service = Service.new(service_params)
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed"
    redirect_to services_path
  end
  
  def update
    @service = Service.find(params[:id])
    if @service.update_attributes(service_params)
      flash[:success] = "Service updated"
      respond_to do |format|
        format.json
        format.html { redirect_to @service }
      end
    else
      render 'edit'
      respond_to do |format|
        format.json
        format.html { render 'edit' }
      end
    end
  end
  
  private
  
  def service_params
    params.require(:service).permit(:name,:photo_file)
  end
  
  def admin_user
    redirect_to(root_url) unless current_user.admin_type != 'none'
  end
  
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/edit.html.erb
<div class="container">
<h3> Add a new Service</h3>
	<%= form_for @service do |f| %>
   	<div class="field">
    	<%= f.label :name %><br>
     	<%= f.text_field :name, class: "input-xxlarge" %><br><br>
   </div>
 
 	<div class="field" >
	<%= image_tag @service.photo_file_url(:small).to_s %>
	<span class="btn success fileinput-button">
	<span><%= t('photos.add_files') %>...</span>
	<%= f.file_field :photo_file, class: "btn btn-default"%><br>
	</span>
	</div>
	
   	<div class="actions">
    <%= f.submit "Update", class: "btn btn-large btn-primary" %>
   	</div>
	<% end %>
</div>

app/views/services/index.html.erb
<% provide(:title, 'All services') %>
<div class="container">
	<h3>All Services</h3>
	<ul class = "services">
		<% @services.each do |service| %>
		<li>
			<%= image_tag service.photo_file.url %>
			<%= link_to service.name, service %>
		        | <%= link_to "edit", edit_service_path(service), method: :get %>
				| <%= link_to "delete", service, method: :delete,
							  			           data: { confirm: "You sure?" } %>
		</li>
		<%end%>
	</ul> <br>
	<div>
		<%= link_to "Add a new service", new_service_path, method: :get %>
	</div>
</div>

app/views/services/new.html.erb
<div class="container">
<h3> Add a new Service</h3>
	<%= form_for @service, url: services_path, html: { multipart: true, role:"form", method:"post" } do |f| %>
   	<div class="field">
    	<%= f.label :name %><br>
     	<%= f.text_field :name, class: "input-xxlarge" %><br><br>
   </div>
 
 	<div class="field" >
	<%= file_field :photo_file, multiple: true %><br>
	</div> 
	
   	<div class="actions">
    <%= f.submit " Create", class: "btn btn-large btn-primary" %>
   	</div>
	<% end %>

</div>

app/views/services/show.html.erb
<div class="container">
	<h3><%= @service.name%></h3>
	<%= image_tag @service.photo_file.url %>
	<div>
		<%= link_to "Show all services", services_path, method: :get %>
	</div>
</div>