config/routes.rb
Rails.application.routes.draw do
  get "services/create"
  root 'static_pages#home'
  resources :users
  resources :sessions, only: [:new,:create,:destroy]
  resources :meeting_rooms, only: [:index,:new,:create,:show]
  resources :images, only: [:index,:create,:destroy]
  resource :settings, only: [:edit,:update]
  resources :suggestions, only: [:new,:create]
  resources :bookings, only: [:index,:new,:create]
  resources :services, only: [:index,:new,:edit,:create,:update,:show]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  MAX_RESERVATION_TIME = 10800
  MIN_RESERVATION_TIME = 1800
  has_many :attendees, dependent: :destroy
  accepts_nested_attributes_for :attendees#, reject_if: proc { |p| p['booking_id'].nil? } , allow_destroy: true
  belongs_to :user
  belongs_to :meeting_room
  default_scope -> { order('created_at DESC') }
  validates :title, presence: true, length: { maximum: 50 }
  validates :user_id, presence: true
  validates :meeting_room_id, presence: true
  validates :priority, presence: true, inclusion: { in: %w(low medium high),
                                       message: "%{value} is not valid" }
  validates :status, presence: true, inclusion: { in: %w(ongoing waiting finished canceled updated),
                                       message: "%{value} is not valid" }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :date_availability, :check_attendees_number
  
  private
  
  def date_availability
    unless start_date.nil? && end_date.nil?
      ##Checks if one of the dates day is saturday or sunday
      if start_date.saturday? || end_date.saturday? || start_date.sunday? || end_date.sunday?
        errors[:base]<< "Cannot make bookings on saturdays or sundays"
      ##Checks if the minimum or maximum reservation time is the correct one
      elsif ((end_date - start_date) > MAX_RESERVATION_TIME || (end_date - start_date) < MIN_RESERVATION_TIME)
        errors[:base]<< "Bookings can only last a maximum of 3 hours or a minimum of 30 minutes"
      ##Cheks if those dates are available
      elsif !Booking.where('((start_date BETWEEN :start_date AND :end_date) AND meeting_room_id = :meeting_room_id) OR ((end_date BETWEEN :start_date AND :end_date) AND meeting_room_id = :meeting_room_id) OR (start_date >= :start_date AND end_date <= :end_date AND meeting_room_id = :meeting_room_id)', start_date: start_date, end_date: end_date, meeting_room_id: meeting_room_id).empty?
        errors[:base]<< "Date is not available"
      end
    end
  end
  
  def check_attendees_number
    errors.add(:attendees, "should have at least one person #{attendees.count}") if attendees_empty?
  end
  
  def attendees_empty?
      attendees.empty? or attendees.all? {|attendee| attendee.marked_for_destruction? }
  end
  
  def self.find_by_date_bookings(my_date)
    bookings = Booking.where("DATE(start_date) = ?", my_date.to_date)
    self.bookings_found(bookings)
  end
  
  def self.get_all_bookings
    bookings = self.all
    self.bookings_found(bookings)
  end
  
  def self.find_by_meeting_room(meeting_room_id)
    bookings = Booking.where("meeting_room_id = ? ",meeting_room_id)
    self.booking_found(bookings)
  end
  
  def self.find_user_bookings(user_id)
    bookings = Booking.where("user_id = ?",user_id)
    self.bookings_found(bookings)
  end
  
  def self.find_by_date_and_meeting_room(my_date,meeting_room_id)
    bookings = Booking.where("DATE(start_date) = ? AND meeting_room_id = ?",my_date.to_date,meeting_room_id)
    self.bookings_found(bookings)
  end
  
  def self.bookings_found(bookings)
    bookings_found = []
    bookings.each do |booking| 
      bookings_found << {
        id: booking.id,
        title: booking.title,
        start_date: booking.start_date,
        end_date: booking.end_date,
        priority: booking.priority,
        status: booking.status,
        comment: booking.comment,
        user_id: booking.user.id,
        owner: booking.user.full_name,
        attendees: booking.attendees
      }
    end
    bookings_found
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  include ErrorCode
  skip_before_action :verify_authenticity_token
  before_action :correct_user, only: :destroy
  before_action :restrict_access, only: [:index,:new,:create,:destroy]
  
  def index
    search[:datetime] = DateTime.strptime(search[:datetime],"%Y-%m-%d %H:%M:%S %z") unless params[:datetime].nil?
    search[:meeting_room_id] = params[:search][:meeting_room_id] unless params[:meeting_room_id].nil?
    searching_by_date_and_meeting_room = !params[:datetime].nil? && !params[:meeting_room_id].nil?
    searching_by_date = !params[:datetime].nil? 
    searching_by_meeting_room = !params[:meeting_room_id].nil?
    searching_by_current_user = !params[:current_user].nil? ? !(params[:current_user].to_i).zero? : false
    
    
    if searching_by_date_and_meeting_room
      respond_to do |format|
        format.html
        format.json {  render :json=>{ bookings: Booking.find_by_date_and_meeting_room(params[:datetime],params[:meeting_room_id]),
                                       success:  true
                                     } , status: 200 }
      end 
    elsif searching_by_date
      respond_to do |format|
        format.html
        format.json {  render :json=>{ bookings: Booking.find_by_date_bookings(search[:datetime]),
                                       success:  true
                                     } , status: 200 }
      end 
    elsif searching_by_current_user
      respond_to do |format|
        format.html
        format.json { render :json=> {bookings: Booking.find_user_bookings(current_user),
                                      success: true 
                                      }, status: 200 }
      end
    else     
      respond_to do |format|
        format.html
        format.json {  render :json=>{ bookings: Booking.get_all_bookings,
                                       success:  true
                                     } , status: 200 }
      end  
  end
  
end
  
  def new
    @booking = current_user.bookings.build
    @meeting_rooms = MeetingRoom.all
  end
  
  def create
    @user=current_user
    @booking=@user.bookings.build(booking_params)
    unless params[:booking][:attendees_attributes].nil?
      params[:booking][:attendees_attributes].each do |x,y|
        puts "Attendee"
        @user=User.find_by_email(y['email'])
        if @user #If the user is in the db just add them to the booking attendees
          @booking_attendee = @booking.attendees.build(user_id: y['user_id'], booking_id: y['booking_id']) 
        else #If the user is not in the db, create them first, then add them to the booking attendees
          @user=User.find_for_ldap(y['email'],"email")
          @booking_attendee = @booking.attendees.build(user_id: @user.id, booking_id: y['booking_id']) if @user.persisted?
        end
      end
     end
      
    if @booking.save
      respond_to do |format|
        format.html { redirect_back_or new_booking_path }
        format.json { render :json=>{ booking: @booking,
                                      success:  true,
                                      } , status: 200 }
      end
    else
      respond_to do |format|
        format.html { redirect_to new_booking_path }
        format.json { render :json=>{ message: @booking.errors.full_messages,
                                      error_code: ErrorCode::BOOKING_VALIDATION
                                      } , status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @micropost.destroy
    redirect_to root_url
  end

  def update
  end
  
  private
  def booking_params
    params.require(:booking).permit(:title,:start_date,:end_date,:meeting_room_id,:priority,:status,:comment,attendees_attributes: [:id,:booking_id,:user_id])
  end
  
  def correct_user #Checks if the booking belongs to the current user
    @booking = current_user.bookings.find_by(id: params[:id])
    redirect_to root_url if @booking.nil?
  end
  
  def search
    @search = []
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
  
  def months
    @months = ['january','february','march','april','may','june','july','august','september','october','november','december']
  end
  
  def stylized_date(booking_date)
    "#{booking_date.day} #{(months[(booking_date.month-1)]).capitalize} #{booking_date.year}"
  end
  
  def stylized_timeframe(start_date,end_date)
    "#{start_date.hour}:#{start_date.min} - #{end_date.hour}:#{end_date.min} hrs"
  end
  
end

app/views/bookings/create.html.erb
<h1>BookingsController#create</h1>
<p>Find me in app/views/bookings_controller/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>BookingsController#destroy</h1>
<p>Find me in app/views/bookings_controller/destroy.html.erb</p>

app/views/bookings/index.html.erb
<script type="text/javascript">
  $(document).ready(function(){
	  var monthNames = [ "January", "February", "March", "April", "May", "June",
	      "July", "August", "September", "October", "November", "December" ];
	  var today = new Date();
	  $("#current-date").val(monthNames[today.getMonth()] + "-" + today.getFullYear());
	  
	  var day = today.getDate();
	  var month = today.getMonth()+1; //January is 0!
	  var year = today.getFullYear();
    $('[data-behaviour~=datepicker]').datepicker({
		defaultDate: today,
		format: "MM-yyyy",
		viewMode: "months", 
		minViewMode: "months",
		todayBtn: true,
	});
	
  })
</script>
<%=render 'shared/left_menu'%>
<div id="content">
<div class="menu-trigger"></div>
<div class="container">
<div class="center">
<h1>Mis Reservaciones</h1><br>
<input type="text" Date data-behaviour='datepicker' id= "current-date"><br><br><br>
<!-- Columns are always 50% wide, on mobile and desktop -->
<div class="row">
  <div class="col-xs-6">
	  <h3>All</h3>
	<ul class = "services">
		<% @my_bookings.each do |booking| %>
		<li>
			<p><%= link_to booking.title, booking %></p>
			<p><%= stylized_date(booking.start_date) %></p>
			<p><%= stylized_timeframe(booking.start_date,booking.end_date)%></p>
		</li>
		<%end%>
	</ul> <br>
  </div>
  <div class="col-xs-6">
	  <h3>Details</h3>
  </div>
</div>

</div>
</div>
</div>

app/views/bookings/new.html.erb
<%=render 'shared/left_menu'%>
<div id="content">
<div class="menu-trigger"></div>
	<div class="center">
		<h1>Book a Meeting Room</h1><br>
		<!-- Stack the columns on mobile by making one full-width and the other half-width -->
				<div class="list-container">
					<div class="list">
					<div class="item">
  					<div class="col-xs-6 col-md-4">
  						<h3>Meeting Rooms</h3>
						<%= form_for @booking, url: bookings_path, html: { role: "form", method: "post" } do |f| %>
							<ul class = "meeting_rooms">
							<%for meeting_room in @meeting_rooms%>
							<li>
								<div class="meeting-room-link">
									<strong><%= link_to meeting_room.name, meeting_room ,class: 'left-pad'%></strong><br>
								</div>
								<div class="right-pad">
									<%= radio_button_tag "booking[meeting_room_id]",meeting_room.id%>
		        					<%= f.label :location, 'Location: ' + meeting_room.location%></div>
									<%= f.label :capacity, 'Capacity: ' + meeting_room.capacity.to_s, class: 'left-pad' %>
							</li>
							<%end%>
							</ul> <br>
						<%end%><br>
						<%=link_to "Confirm Reservation", '#confirm-booking',id: "start-booking", class: 'btn btn-primary btn-lg'%>
  		  			</div>
  			  		<div id="services-list" class="col-xs-12 col-md-8">
  						<h3>Details</h3>
						<!-- 2. Add images to <div class="fotorama"></div>. -->
						<div id="gallery" data-auto="false" >
					    	<%= image_tag 'dafault.png' %>
						</div>
						<h3>Services</h3>
						<p id="default-meeting-description">Displays the services availabe for each meeting room</p>
						<ul id="services-preview"></ul>
  					</div>
				</div>
				<div class="item">
  					<div class="col-xs-6 col-md-4">
						<%=link_to "Go Back", '#start-booking', class: 'btn btn-primary btn-lg'%>
					</div>
  					<div class="col-xs-6 col-md-4">
					</div>
				</div>
			</div>
		</div>
</div>

<%=javascript_include_tag 'preview.js'%>

app/views/bookings/update.html.erb
<h1>BookingsController#update</h1>
<p>Find me in app/views/bookings_controller/update.html.erb</p>