config/routes.rb
Rails.application.routes.draw do
  get "services/create"
  root 'static_pages#home'
  resources :users
  resources :sessions, only: [:new,:create,:destroy]
  resources :meeting_rooms, only: [:index,:new,:create,:show]
  resources :images, only: [:index,:create,:destroy]
  resource :settings, only: [:edit,:update]
  resources :suggestions, only: [:new,:create]
  resources :bookings, only: [:index,:new,:create]
  resources :services, only: [:index,:new,:edit,:create,:update,:show]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :restrict_access, only: [:edit, :update]
  
  def edit
    @security_user=!User.find_by_admin_type("security").nil? ? User.find_by_admin_type("security") : User.new
    @administrative_user=!User.find_by_admin_type("administrative").nil? ? User.find_by_admin_type("administrative") : User.new
    @parking_user =!User.find_by_admin_type("parking").nil? ? User.find_by_admin_type("parking") : User.new
  end
  
  def update
    @security_user=User.find_by_email(params[:security_user][:email]) if !params[:security_user].nil?
    @administrative_user= User.find_by_email(params[:administrative_user][:email]) if !params[:administrative_user].nil?
    @parking_user=User.find_by_email(params[:parking_user][:email]) if !params[:parking_user].nil?
    @security_user.update_attribute(:admin_type, "security") if !@security_user.nil?
    @administrative_user.update_attribute(:admin_type, "administrative") if !@administrative_user.nil?
    @parking_user.update_attribute(:admin_type, "parking") if !@parking_user.nil?
    flash.now[:success]="Updated!"
    redirect_to edit_settings_path
  end
end

app/views/settings/edit.html.erb
<%=render 'shared/left_menu'%>
<div id="content">
<div class="menu-trigger"></div>
<div class="container">
<div class="center">
	<h3>Update Administrators</h3>
	  
    <%= form_for(:security_user,url: settings_path,html: {role: "form",method: "put"}) do |f| %>
	<div class="form-group">
      <%= f.label :email,"Security Email" %>
      <%= f.text_field :email %>

      <%= f.submit "Update", class: "btn btn-large btn-primary" %>
  </div>
    <% end %>
	
    <%= form_for(:administrative_user,url: settings_path,html: {role: "form",method: "put"}) do |f| %>
	<div class="form-group">

      <%= f.label :email,"Administrative Email" %>
      <%= f.text_field :email %>

      <%= f.submit "Update", class: "btn btn-large btn-primary" %>
	  </div>
	  
    <% end %>
	
    <%= form_for(:parking_user,url: settings_path,html: {role: "form",method: "put"}) do |f| %>
	<div class="form-group">

      <%= f.label :email,"Parking Email" %>
      <%= f.text_field :email %>

      <%= f.submit "Update", class: "btn btn-large btn-primary" %>
    <% end %>
    </div>
</div>
</div></div>