config/routes.rb
Rails.application.routes.draw do
  get "services/create"
  root 'static_pages#home'
  resources :users
  resources :sessions, only: [:new,:create,:destroy]
  resources :meeting_rooms, only: [:index,:new,:create,:show]
  resources :images, only: [:index,:create,:destroy]
  resource :settings, only: [:edit,:update]
  resources :suggestions, only: [:new,:create]
  resources :bookings, only: [:index,:new,:create]
  resources :services, only: [:index,:new,:edit,:create,:update,:show]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  belongs_to :user
  validates :comment, presence: true
  validates :user_id, presence: true
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  include ErrorCode
  skip_before_action :verify_authenticity_token
  before_action :restrict_access, only: [:new, :create]
  
  def new
    @suggestion=Suggestion.new
  end
  
  
  def create
    @user=current_user
    @suggestion= @user.suggestions.build(suggestion_params(params))
    if @suggestion.save
      respond_to do |format|
        format.html { redirect_back_or root_path }
        format.json { render :json=>{ comment: @suggestion.comment,
                                      user_id: @user.id,
                                      success:  true
                                      } , status: 200 }
       end
     else
       respond_to do |format|
         flash.now[:error] = 'Invalid email/password combination'
         format.html { render 'new' }
         format.json { render :json=> { success: false,
                                        message: @suggestion.errors.full_messages,
                                        error_code: ErrorCode::SUGGESTION_VALIDATION
                                      } , status: :unprocessable_entity }
        end
      end
  end
  
  private
  def suggestion_params(params)
      params.require(:suggestion).permit(:comment,:user_id)
  end
end

app/views/suggestions/new.html.erb
<%=render 'shared/left_menu'%>
<div id="content">
<div class="menu-trigger"></div>
<div class="container">
<div class="center">
	<h3>Create Suggestion</h3>
	  
    <%= form_for(@suggestion,url: suggestions_path,html: {role: "form",method: "post"}) do |f| %>
	<div class="form-group">
      <%= f.label :comment,"Comment" %><br>
      <%= f.text_area :comment ,cols: "60", rows: "10"%> <br>

      <%= f.submit "Create", class: "btn btn-large btn-primary" %>
  	</div>
    <% end %>

    </div>
</div>
</div>